### ISSUE TITLE
service worker self is not defined!!

### ISSUE THREAD

**Issue by nwabdou85** [TomasDePomas/notifier#1]
Hi, 
I try to implement your package in my meteor reactjs app, but it throw an error : self is not defined; 

How to fix it , please ?? can I use it with react also or require some more config??

**Comment by TomasDePomas** [comment]
Did you put the service-worker in the correct directory? Because it sounds like meteor might be trying to compile the serviceworker file.

**Comment by nwabdou85** [comment]
ooops, I move it to public folder now and it's ok; 
Can I have an example using reactjs and meteor with your package please ?
I tried to send notific with your example below but dosent work.
 Notifier.send(
    'Hallo', 
    'g8aQSJunen44ZK5nn'
);

I don't understand when and when to user Notifier.start,Notifier.setConfig,Notifier.subscribe(), Notifier.unsubscribe() and Notifier.windowNotification.

may be with a working example ll be easy to understand.
Thanks

**Comment by TomasDePomas** [comment]
I have no experience with working with Meteor in combination with React. To be honest it has been a while since I worked with this package.

I'll setup an example project for you to show how the notifications work with a plain meteor project.

**Comment by TomasDePomas** [comment]
I have added a demo project here:
https://github.com/TomasDePomas/notifier_demo, its really basic but i hope this helps you to setup your own implementation, please let me know if things are clearer now.

**Comment by nwabdou85** [comment]
@TomasDePomas  Thank's à lot,
